version: 0.0
os: linux
files:
  - source: aws_codedeploy_demo
    destination: /root/kelu_demo/
hooks:
  BeforeInstall:
    - location: start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server
      timeout: 300
      runas: root

